{{ config(
    materialized='view'
) }}

{% set unpivot_cols %}
    {% for i in range(1,145) %}
        COL_{{ i }}{% if not loop.last %},{% endif %}
    {% endfor %}
{% endset %}

WITH CTE_PERIOD AS (
    SELECT DISTINCT 
        RAW_COL,
        COL,
        REGEXP_SUBSTR(RAW_COL,'\\d+') 
            || LPAD(MONTH(TO_DATE(REGEXP_SUBSTR(RAW_COL,'\\w+',1,2),'MON')),2,'0') AS PERIOD
    FROM {{ source('landing','STG') }}
    UNPIVOT(RAW_COL FOR COL IN ({{ unpivot_cols }}))
    WHERE ATC1 ILIKE 'ATC1'
),

CTE_MOL_AGG AS (
    SELECT 
        ATC1, ATC2, ATC3, ATC4,
        NFC1, NFC12, NFC123,
        CORPORATION, MANUFACTURER, PRODUCT,
        LISTAGG(MOLECULES,'!') AS MOLECULES_AGG,
        MONO_COMBI, PACK, DOSAGE, LAUNCH_DATE
    FROM {{ ref('VW_STG_DZ') }}
    GROUP BY 1,2,3,4,5,6,7,8,9,10,12,13,14,15
)

SELECT 
    'ALGERIA' AS COUNTRY,
    'LMNPA'  AS PANEL,
    'RETAIL' AS CHANNEL,
    COUNTRY||'_'||PANEL AS FILE_GROUP,
    'M' AS FREQUENCY,
    1 AS LATEST_FLAG,
    MAX(PERIOD) OVER(PARTITION BY COUNTRY,PANEL) AS END_PERIOD,
    MIN(PERIOD) OVER(PARTITION BY COUNTRY,PANEL) AS MIN_PERIOD,
    MD5(COUNTRY||'_'||PANEL||'_'||END_PERIOD) AS PROCESS_ID,
    COUNTRY||'_'||PANEL||'_'||END_PERIOD AS FILE_NAME,
    ATC1, ATC2, ATC3, ATC4,
    NFC1, NFC12, NFC123,
    CORPORATION, MANUFACTURER, PRODUCT,
    MOLECULES, MOLECULES_AGG,
    MONO_COMBI, PACK, DOSAGE, LAUNCH_DATE, RX,
    PERIOD,
    SUM("'LC'")   AS LC,
    SUM("'UNITS'") AS UNITS
FROM (
    SELECT 
        A.ATC1, A.ATC2, A.ATC3, A.ATC4,
        A.NFC1, A.NFC12, A.NFC123,
        A.CORPORATION, A.MANUFACTURER, A.PRODUCT,
        MOLECULES, MOLECULES_AGG,
        A.MONO_COMBI, A.PACK, A.DOSAGE,
        RIGHT(IFF(LEN(A.LAUNCH_DATE)=6,A.LAUNCH_DATE,0||A.LAUNCH_DATE),4)
            || LEFT(IFF(LEN(A.LAUNCH_DATE)=6,A.LAUNCH_DATE,0||A.LAUNCH_DATE),2) AS LAUNCH_DATE,
        RX,
        CASE  
            WHEN UPPER(SPLIT_PART(RAW_COL,'_',1)) LIKE '%UNIT%' THEN 'UNITS'
            ELSE 'LC'
        END AS RAW_COL,
        TO_NUMBER(PERIOD) AS PERIOD,
        VALUE
    FROM {{ ref('VW_STG_DZ') }}
    UNPIVOT(VALUE FOR CALENDAR_ID IN ({{ unpivot_cols }})) A
    JOIN CTE_PERIOD B ON A.CALENDAR_ID = B.COL
    JOIN CTE_MOL_AGG M USING (
        ATC1, ATC2, ATC3, ATC4,
        NFC1, NFC12, NFC123,
        CORPORATION, MANUFACTURER, PRODUCT,
        MONO_COMBI, PACK, DOSAGE, LAUNCH_DATE
    )
) F
PIVOT(SUM(VALUE) FOR RAW_COL IN ('LC','UNITS'))
GROUP BY 
    ATC1, ATC2, ATC3, ATC4,
    NFC1, NFC12, NFC123,
    CORPORATION, MANUFACTURER, PRODUCT,
    MOLECULES, MOLECULES_AGG,
    MONO_COMBI, PACK, DOSAGE, LAUNCH_DATE, RX,
    PERIOD
HAVING COALESCE(SUM("'LC'"),0) + COALESCE(SUM("'UNITS'"),0) != 0






