{{ config(
    materialized='view'
) }}
SELECT TRIM(ATC1) AS ATC1
,TRIM(ATC2) AS ATC2
,TRIM(ATC3) AS ATC3
,TRIM(ATC4) AS ATC4
,TRIM(NFC1) AS NFC1
,TRIM(NFC12) AS NFC12
,TRIM(NFC123) AS NFC123
,TRIM(LABORATOIRE) AS CORPORATION
,TRIM(LABORATOIRE) AS MANUFACTURER
,TRIM(PRODUIT) AS PRODUCT
,TRIM(MOLECULE) AS MOLECULES
,TRIM(MONO_COMBI) AS MONO_COMBI
,TRIM(PRESENTATION) AS PACK
,TRIM(DOSAGE) AS DOSAGE
,DATE_DE_LANCEMENT AS LAUNCH_DATE
,'OTC' AS RX
 ,{% for i in range(1, 145) %}
        ZEROIFNULL(REPLACE(COL_{{ i }}, ' ', '')) AS COL_{{ i }}{% if not loop.last %},{% endif %}
    {% endfor %}
FROM {{ source('landing', 'STG') }}
WHERE UPPER(ATC1) !='ATC1'
AND UPPER(ATC1) NOT LIKE 'GRAND%'